### PR TITLE
Add missing fields to PtctlPacket

### PR DESCRIPTION
**Pull request by plsfixrito**

### CODE REVIEW

**Comment by Rutherther** [comment]
I think it looks similar to end of walk packets, it's likely speed of the entity. Not always 9, changes for different mates

**Comment by Rutherther** [comment]
It looks to me that the speed is not sent from the server. It probably has to be obtained from nostale data files, from `IInfoService.GetMonsterInfoAsync`

**Comment by plsfixrito** [comment]
> I think it looks similar to end of walk packets, it's likely speed of the entity. Not always 9, changes for different mates

I renamed the fields to their names.

> It looks to me that the speed is not sent from the server. It probably has to be obtained from nostale data files, from `IInfoService.GetMonsterInfoAsync`

The speed property type is inconsistent is the project. In packets sometimes defined as byte other times as short and in ILivingEntity it is an integer. I think all speed properties should use the same type.

**Comment by Rutherther** [comment]
You are absolutely right, I think there are more inconsistencies like that. Sadly I did not manage to make it consistent yet even though I wanted.

**Pull request merged**
